import type { Badge, Person, Quest } from "./types";

export const QUESTS: Quest[] = [
  {
    id: "q-sunrise-run",
    title: "Sunrise 5K along the Embarcadero",
    emoji: "🌅",
    category: "Fitness",
    vibe: "High-energy",
    difficulty: 2,
    xp: 220,
    durationMin: 55,
    distanceKm: 1.4,
    neighborhood: "Embarcadero",
    startsAt: "Sat · 6:30 AM",
    partySize: { min: 3, max: 8, current: 5 },
    match: 96,
    host: { name: "Maya R.", avatar: "MR", level: 14 },
    attendees: [
      { name: "Diego", avatar: "DV" },
      { name: "Priya", avatar: "PS" },
      { name: "Eli", avatar: "EM" },
      { name: "Noor", avatar: "NA" },
    ],
    tags: ["beginner-friendly", "coffee after", "pace 6:00/km"],
    blurb:
      "Easy pace, real conversation, and the best skyline in the city. We finish with a flat white at Sightglass.",
    reasoning:
      "You ran 4× last week and your sleep score peaks early. 4 of your matched-vibes are going.",
  },
  {
    id: "q-bouldering",
    title: "Beginner bouldering night",
    emoji: "🧗",
    category: "Fitness",
    vibe: "Adventurous",
    difficulty: 3,
    xp: 340,
    durationMin: 120,
    distanceKm: 3.2,
    neighborhood: "Dogpatch",
    startsAt: "Wed · 7:00 PM",
    partySize: { min: 2, max: 6, current: 4 },
    match: 91,
    host: { name: "Jules T.", avatar: "JT", level: 22 },
    attendees: [
      { name: "Ana", avatar: "AC" },
      { name: "Theo", avatar: "TK" },
      { name: "Sam", avatar: "SF" },
    ],
    tags: ["v0–v3", "rentals included", "snacks"],
    blurb:
      "We tackle three problems together, then hit the bao spot next door. Belay-free; pads and crash mats provided.",
    reasoning:
      "Matches your ‘try-something-new’ goal and 3 friends-of-friends are joining.",
  },
  {
    id: "q-pottery",
    title: "Wheel-throwing pottery jam",
    emoji: "🏺",
    category: "Creative",
    vibe: "Chill",
    difficulty: 2,
    xp: 180,
    durationMin: 90,
    distanceKm: 2.0,
    neighborhood: "Mission",
    startsAt: "Sun · 2:00 PM",
    partySize: { min: 2, max: 5, current: 3 },
    match: 88,
    host: { name: "Ines V.", avatar: "IV", level: 9 },
    attendees: [
      { name: "Liam", avatar: "LO" },
      { name: "Zara", avatar: "ZK" },
    ],
    tags: ["clay included", "all skill levels", "free aprons"],
    blurb:
      "Two hours on the wheel with chill house in the background. Take home one piece, or trade with a stranger.",
    reasoning:
      "You saved 2 ceramics reels this month. Ines’ vibe matches your ‘slow Sundays’ tag.",
  },
  {
    id: "q-night-market",
    title: "Night market food crawl",
    emoji: "🍜",
    category: "Food",
    vibe: "Social",
    difficulty: 1,
    xp: 140,
    durationMin: 100,
    distanceKm: 0.8,
    neighborhood: "SoMa",
    startsAt: "Fri · 8:30 PM",
    partySize: { min: 4, max: 10, current: 7 },
    match: 84,
    host: { name: "Priya S.", avatar: "PS", level: 12 },
    attendees: [
      { name: "Marc", avatar: "MD" },
      { name: "Han", avatar: "HW" },
      { name: "Tess", avatar: "TG" },
      { name: "Owen", avatar: "OL" },
      { name: "Rhea", avatar: "RB" },
      { name: "Kai", avatar: "KO" },
    ],
    tags: ["8 stalls", "split tabs", "vegan-friendly"],
    blurb:
      "Eight stalls, one shared spreadsheet, splitting bites and stories. Bring an open palate.",
    reasoning:
      "You opened 3 ‘new restaurant’ posts this week. Your party loves spicy.",
  },
  {
    id: "q-vinyl-listen",
    title: "Vinyl listening party — Side B only",
    emoji: "🎧",
    category: "Music",
    vibe: "Chill",
    difficulty: 1,
    xp: 110,
    durationMin: 75,
    distanceKm: 4.1,
    neighborhood: "Lower Haight",
    startsAt: "Thu · 9:00 PM",
    partySize: { min: 3, max: 6, current: 3 },
    match: 82,
    host: { name: "Eli M.", avatar: "EM", level: 7 },
    attendees: [
      { name: "Cory", avatar: "CB" },
      { name: "Iris", avatar: "IH" },
    ],
    tags: ["BYO record", "low-light", "no phones"],
    blurb:
      "We each bring a record, listen to Side B in the dark, talk after. Last week was Talk Talk → Khruangbin.",
    reasoning:
      "Your ‘deep listening’ tag and night-owl pattern align with this group.",
  },
  {
    id: "q-yoga-park",
    title: "Park flow + matcha",
    emoji: "🧘",
    category: "Wellness",
    vibe: "Chill",
    difficulty: 2,
    xp: 160,
    durationMin: 70,
    distanceKm: 1.1,
    neighborhood: "Dolores Park",
    startsAt: "Sat · 9:30 AM",
    partySize: { min: 3, max: 12, current: 8 },
    match: 79,
    host: { name: "Noor A.", avatar: "NA", level: 18 },
    attendees: [
      { name: "Sage", avatar: "SP" },
      { name: "Devon", avatar: "DB" },
      { name: "Maya", avatar: "MR" },
      { name: "Alec", avatar: "AC" },
      { name: "Ben", avatar: "BM" },
    ],
    tags: ["bring a mat", "donation-based", "post-flow matcha"],
    blurb:
      "Vinyasa under the trees, then a slow walk to Stonemill for matcha and intros.",
    reasoning:
      "Your weekday stress score is elevated. 5 attendees share your ‘grounded mornings’ tag.",
  },
  {
    id: "q-kayak",
    title: "Twilight kayak around the bay",
    emoji: "🛶",
    category: "Outdoors",
    vibe: "Adventurous",
    difficulty: 3,
    xp: 280,
    durationMin: 95,
    distanceKm: 6.8,
    neighborhood: "Sausalito",
    startsAt: "Sat · 5:45 PM",
    partySize: { min: 2, max: 4, current: 2 },
    match: 87,
    host: { name: "Theo K.", avatar: "TK", level: 11 },
    attendees: [{ name: "Maya", avatar: "MR" }],
    tags: ["beginner ok", "kayak rental", "sunset"],
    blurb:
      "Two hours on glass-flat water at golden hour. We raft up midway, share a thermos, swap quest stories.",
    reasoning: "You haven’t logged ‘water’ this season. Theo’s pace matches yours.",
  },
  {
    id: "q-improv",
    title: "Drop-in improv: Yes, And Sundays",
    emoji: "🎭",
    category: "Learn",
    vibe: "Social",
    difficulty: 2,
    xp: 200,
    durationMin: 90,
    distanceKm: 2.7,
    neighborhood: "Hayes Valley",
    startsAt: "Sun · 6:30 PM",
    partySize: { min: 4, max: 12, current: 9 },
    match: 76,
    host: { name: "Cory B.", avatar: "CB", level: 6 },
    attendees: [
      { name: "Iris", avatar: "IH" },
      { name: "Marc", avatar: "MD" },
      { name: "Tess", avatar: "TG" },
      { name: "Owen", avatar: "OL" },
      { name: "Han", avatar: "HW" },
      { name: "Sam", avatar: "SF" },
    ],
    tags: ["zero experience", "warm room", "drinks after"],
    blurb:
      "60 minutes of guided games. We laugh too loudly, then debrief over pintxos at Maven.",
    reasoning:
      "Your conversation goal is set to ‘confidence’. Improv compounds it fast.",
  },
];

export const PEOPLE: Person[] = [
  {
    id: "p-maya",
    name: "Maya",
    age: 28,
    avatar: "MR",
    bio: "Trail runner, slow-coffee defender. Looking for sunrise crews and bookstore wanderers.",
    vibe: "High-energy",
    match: 94,
    level: 14,
    xp: 4380,
    badges: ["🌅 Early Bird", "🏃 Pacekeeper", "🤝 Connector"],
    interests: ["Running", "Espresso", "Memoirs", "Surfing"],
    voicePreview: {
      duration: 28,
      text: "Hi — I'm Maya. I'd rather run a hilly 5K than do small talk at a bar. Coffee after is non-negotiable though.",
    },
    recentQuests: [
      { title: "Sunrise 5K", emoji: "🌅" },
      { title: "Park flow", emoji: "🧘" },
      { title: "Twilight kayak", emoji: "🛶" },
    ],
    online: true,
    distanceKm: 0.9,
  },
  {
    id: "p-diego",
    name: "Diego",
    age: 31,
    avatar: "DV",
    bio: "Architect by day, vinyl hoarder by night. Prefer 2-person quests; trade me your weirdest record.",
    vibe: "Chill",
    match: 89,
    level: 11,
    xp: 3120,
    badges: ["🎧 Deep Listener", "🌃 Night Owl", "🧱 Builder"],
    interests: ["Brutalism", "Jazz", "Cycling", "Ramen"],
    voicePreview: {
      duration: 22,
      text: "Hey, Diego here. I'll talk about buildings until you stop me. I never stop me.",
    },
    recentQuests: [
      { title: "Vinyl listen", emoji: "🎧" },
      { title: "Night market", emoji: "🍜" },
    ],
    online: false,
    distanceKm: 2.4,
  },
  {
    id: "p-priya",
    name: "Priya",
    age: 26,
    avatar: "PS",
    bio: "Hosts the loudest dinner table in SoMa. Looking for foodies, storytellers, and one (1) hiking partner.",
    vibe: "Social",
    match: 92,
    level: 12,
    xp: 3640,
    badges: ["🍜 Crawl Captain", "🔥 Heat Seeker", "🎤 Storyteller"],
    interests: ["Sichuan", "Trail mixers", "Karaoke", "Group chats"],
    voicePreview: {
      duration: 31,
      text: "Priya. I bring a spreadsheet to dinner and zero shame. If you can't handle ranked dumplings, swipe left.",
    },
    recentQuests: [
      { title: "Night market", emoji: "🍜" },
      { title: "Improv Sunday", emoji: "🎭" },
    ],
    online: true,
    distanceKm: 1.6,
  },
  {
    id: "p-jules",
    name: "Jules",
    age: 33,
    avatar: "JT",
    bio: "Climbs V5 on a good day. Hosts beginner bouldering nights — your first send is on me.",
    vibe: "Adventurous",
    match: 86,
    level: 22,
    xp: 7220,
    badges: ["🧗 Send Master", "🦾 Belay Buddy", "🌲 Outsider"],
    interests: ["Climbing", "Long drives", "Hot springs", "Dogs"],
    voicePreview: {
      duration: 26,
      text: "Jules — I will absolutely cheer like a maniac when you top your first V0. Sorry in advance.",
    },
    recentQuests: [
      { title: "Bouldering night", emoji: "🧗" },
      { title: "Twilight kayak", emoji: "🛶" },
    ],
    online: true,
    distanceKm: 3.0,
  },
  {
    id: "p-ines",
    name: "Ines",
    age: 29,
    avatar: "IV",
    bio: "Ceramicist, slow walker, terrible at small talk and proud of it.",
    vibe: "Chill",
    match: 85,
    level: 9,
    xp: 2470,
    badges: ["🏺 Maker", "🌿 Slow Living"],
    interests: ["Pottery", "Tea", "Botany", "Sundays"],
    voicePreview: {
      duration: 19,
      text: "Hi, I'm Ines. My quests usually involve clay, tea, and exactly one good conversation.",
    },
    recentQuests: [
      { title: "Pottery jam", emoji: "🏺" },
      { title: "Park flow", emoji: "🧘" },
    ],
    online: false,
    distanceKm: 1.8,
  },
  {
    id: "p-theo",
    name: "Theo",
    age: 30,
    avatar: "TK",
    bio: "Kayak guide on weekends, product designer on weekdays. Sunset > sunrise, fight me.",
    vibe: "Adventurous",
    match: 83,
    level: 11,
    xp: 3010,
    badges: ["🛶 Waterborne", "🌅 Sunset Caller"],
    interests: ["Kayaking", "Cold plunges", "Indie games", "Tacos"],
    voicePreview: {
      duration: 24,
      text: "Theo here. Quick paddle, slow conversation. Bring questions, I'll bring snacks.",
    },
    recentQuests: [
      { title: "Twilight kayak", emoji: "🛶" },
      { title: "Bouldering night", emoji: "🧗" },
    ],
    online: true,
    distanceKm: 4.2,
  },
];

export const BADGES: Badge[] = [
  { id: "b-01", name: "First Quest", emoji: "🚀", description: "Completed your first quest.", earned: true },
  { id: "b-02", name: "Early Bird", emoji: "🌅", description: "5 quests before 8am.", earned: true },
  { id: "b-03", name: "Connector", emoji: "🤝", description: "Brought a friend on 3 quests.", earned: true },
  { id: "b-04", name: "Pacekeeper", emoji: "🏃", description: "Logged 50km of run-quests.", earned: false },
  { id: "b-05", name: "Storyteller", emoji: "🎤", description: "Hosted 3 quests with 5★ vibe.", earned: false },
  { id: "b-06", name: "Sendmaster", emoji: "🧗", description: "Topped a V3 problem in a quest.", earned: false },
  { id: "b-07", name: "Quest Streak", emoji: "🔥", description: "Quests 4 weeks in a row.", earned: true },
  { id: "b-08", name: "Voicelander", emoji: "🎙️", description: "Sent 10 voice previews.", earned: false },
];

export const ME = {
  name: "Alex",
  handle: "@alex",
  avatar: "AX",
  level: 7,
  xp: 1820,
  xpToNext: 2200,
  streak: 3,
  vibe: "Adventurous" as const,
  questsCompleted: 12,
  friendsMade: 9,
  hoursOutside: 38,
};

export function questById(id: string) {
  return QUESTS.find((q) => q.id === id);
}

export function personById(id: string) {
  return PEOPLE.find((p) => p.id === id);
}
